//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDemo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alarme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alarme()
        {
            this.Zonas = new HashSet<Zona>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string EnderecoInstalacao { get; set; }
        public System.DateTime DataInstalacao { get; set; }
        public int ContratoId { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zona> Zonas { get; set; }
    }
}
